#!/bin/bash
# run bnac background

read -p "Please input your email passwd:" email_passwd
read -p "input your RSA token passcode:" passcode
passwd="${email_passwd}${passcode}"

tmux new-session -s login-relay -d 
tmux send-keys -t login-relay 'bash' C-m
tmux send-keys -t login-relay "hi dev -e ${email_passwd} -p ${passcode}" C-m 
#tmux attach -t login-relay
