#!/usr/bin/expect

## usage : ./relay-ssh server user password token
## argv 0 : server
## argv 1 : user
## argv 2 : password
## argv 3 : token

set server [lindex $argv 0]
set user [lindex $argv 1]
set password [lindex $argv 2]
set token [lindex $argv 3]

## login relay
spawn ssh relay.xiaomi.com -l $user

if { 0 != [ llength $password ] } {
  expect -timeout 2 "password:"
  send "$password\n"
}

if { 0 != [ llength $token ] } {
  expect -timeout 2 "token:"
  send "$token\n"
}

interact -o -nobuffer "$" return

send "shell\n"

## sudo user
#expect "$"
#send "sudo -iu $user\n"
interact
