#!/usr/bin/expect

## usage : ./relay-ssh server user
## argv 0 : server
## argv 1 : user

set server [lindex $argv 0]
set user [lindex $argv 1]
set passcode [lindex $argv 2 ]

## login relay
spawn ssh relay02.baidu.com -l $env(BAIDU_ACCOUNT)

## passcode length is 10 , is not equal 10 , expect input PASSCODE
if { 0 != [ llength $passcode ] } {
  expect -timeout 2 "PASSCODE:"
  send "$passcode\n"
}

interact -o -nobuffer "$" return

## ssh server
send "ssh $server\n"

## sudo user
expect "$"
send "sudo -iu $user\n"
interact
